language: php
cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/symfony-bridge/.phpunit
warnings_are_errors: false
services:
    - mysql
php:
    - 7.4
env:
    global:
        - CC_TEST_REPORTER_ID=$CC_TR_ID
        - JWT_PASSPHRASE=$JWT_KEY_PASS
before_script:
    - sudo mkdir -p config/jwt
    - sudo openssl genrsa -passout pass:$JWT_KEY_PASS -out config/jwt/private-test.pem -aes256 4096
    - sudo openssl rsa -passin pass:$JWT_KEY_PASS -pubout -in config/jwt/private-test.pem -out config/jwt/public-test.pem
    # Add Code Climate test reporter to get test coverage
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    # Enable code coverage for xdebug
    # https://docs.travis-ci.com/user/languages/php/
    - echo 'xdebug.mode="coverage"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
before_install:
    # Copy content from .env.travis to .env.test
    - cp .env.travis .env.test
install:
    - composer self-update
    - composer install --prefer-dist --no-interaction --ignore-platform-reqs
    # https://stackoverflow.com/questions/55504641/travis-ci-error-1045-28000-access-denied-for-user-rootlocalhost-using#answer-55506528
    - sudo mysql -e "USE mysql; UPDATE user SET authentication_string=PASSWORD('') WHERE user='root'; UPDATE user SET plugin='mysql_native_password'; FLUSH PRIVILEGES;"
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:update --force --env=test
    - php bin/console cache:clear -n --env=test
    - php bin/console doctrine:fixtures:load -n --env=test
script:
    - php bin/phpunit --coverage-text --colors
after_script:
    - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT
# No notification about build state
notifications:
    email: false