doctrine:
    orm:
        metadata_cache_driver:
            type: service
            id: app.cache.doctrine_provider
        query_cache_driver:
            type: service
            id: app.cache.doctrine_provider
        # Result cache is directly managed in classes with custom adapter
        # with Symfony cache depending on called queries
        #result_cache_driver:
            #type: service
            #id: app.cache.doctrine_provider

# https://symfony.com/doc/current/components/cache/adapters/doctrine_adapter.html
# https://www.doctrine-project.org/projects/doctrine-orm/en/current/reference/caching.html
# https://symfony.com/doc/current/components/cache/cache_invalidation.html
services:
    # add Doctrine cache tag aware adapter to manage its cache
    app.cache.doctrine_tag_aware_adapter:
        class: Symfony\Component\Cache\Adapter\TagAwareAdapter
        arguments:
            - '@app.cache.doctrine_adapter'

    # add Doctrine cache adapter to manage its cache
    app.cache.doctrine_adapter:
        class: Symfony\Component\Cache\Adapter\DoctrineAdapter
        arguments:
            $provider: '@app.cache.doctrine_provider'
            $namespace: 'DoctrineCachedData'
            $defaultLifetime: 3600

    # add Doctrine cache provider associated to custom adapter
    app.cache.doctrine_provider:
        class: Doctrine\Common\Cache\SQLite3Cache
        arguments:
            - '@app.cache.doctrine_driver.sqlite'
            - 'doctrine_data'

    # add Doctrine cache SQLite cache driver associated to custom provider
    app.cache.doctrine_driver.sqlite:
        class: \SQLite3
        arguments:
            - '%api_doctrine_cache_directory_path%/%kernel.environment%_data.sqlite'

framework:
    cache:
        # Define cache pools if needed
        #pools: