# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    api_and_version_path_prefix: 'api/v1'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # add a custom expression functions provider to JMS serializer
    App\Services\JMS\ExpressionLanguage\ExpressionFunctionsProvider:
        tags:
            - jms.expression.function_provider

    # customise JWT payload thanks to Lexik listener
    App\Services\Lexik\Listener\JWTCreatedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created}

    # customise JMS object constructor to enforce use of entity constructor for deserialization
    jms_serializer.unserialize_object_constructor:
        alias: jms_serializer.unserialize_object_constructor.custom
    jms_serializer.unserialize_object_constructor.custom:
        class: App\Services\JMS\EntityConstruction\ObjectConstructor

